### Find All Runs
GET http://localhost:8080/runnerz/api/run
Authorization: Bearer {{jwt}}


### Find Run By ID
GET http://localhost:8080/runnerz/api/run/10
Authorization: Bearer {{jwt}}


### Create New Run
POST http://localhost:8080/runnerz/api/run
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "title": "Sunday Run - HoHo",
  "startedOn": "2024-12-12T15:00:12.49766",
  "completedOn": "2024-12-12T15:20:12.497678",
  "miles": 26,
  "location": "INDOOR"
}


### Update an Existing Run
PUT http://localhost:8080/runnerz/api/run/11
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "title": "Sunday Run - HoHo"
}


### Delete a Run
DELETE http://localhost:8080/runnerz/api/run/11
Authorization: Bearer {{jwt}}


### Create New User
POST http://localhost:8080/runnerz/api/user
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "username": "test_1",
  "password": "test_1",
  "roles": ["", "USER", "NOT A VALID ROLE"]
}

### Register User
POST http://localhost:8080/runnerz/api/user/register
Content-Type: application/json

{
  "username": "test_2",
  "password": "test_2",
  "roles": ["", "USER", "NOT A VALID ROLE"]
}


### Find All Users
GET http://localhost:8080/runnerz/api/user
Authorization: Bearer {{jwt}}


### Authenticate
POST http://localhost:8080/runnerz/api/auth/authenticate
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}
> {%
client.global.set("jwt", response.body.jwt);
%}